nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.8.1.cjs

# Ensure Yarn's npm plugin targets the real npm registry for publishing.
npmRegistryServer: "https://registry.npmjs.org"
npmAlwaysAuth: true
