/**
 * This file was auto-generated by pocketbase-zod-schema.
 * Do not modify it manually.
 */

export interface ProjectsRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: "Projects";
  title: string;
  content: string;
  status: "draft" | "active" | "complete" | "fail";
  summary?: string;
  OwnerUser: string;
  SubscriberUsers: string[];
}

export interface ProjectsResponse extends ProjectsRecord {
  expand?: {
    OwnerUser?: UsersResponse;
    SubscriberUsers?: UsersResponse[];
  };
}

export interface UsersRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: "Users";
  name?: string;
  avatar?: string;
}

export interface UsersResponse extends UsersRecord {
}

export type CollectionResponses = {
  Projects: ProjectsResponse;
  Users: UsersResponse;
};

import PocketBase from "pocketbase";
import { RecordService } from "pocketbase";

export interface TypedPocketBase extends PocketBase {
  collection(idOrName: string): RecordService;
  collection(idOrName: "Projects"): RecordService<ProjectsResponse>;
  collection(idOrName: "Users"): RecordService<UsersResponse>;
}
