#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

# Skip checks for merge commits
if [ -f .git/MERGE_HEAD ] || [ -n "$(git log -1 --pretty=%B | grep -E '^Merge ')" ]; then
  exit 0
fi

# Run linting and type checking before commit
yarn lint
yarn typecheck

# Run tests
yarn test